- include: install/{{ ansible_os_family | lower }}.yml

- name: Install InfluxDB python client package [PIP]
  pip:
    name: influxdb
    state: "{{ influxdb_python_client_state | default(omit) }}"
    version: "{{ influxdb_python_client_version | default(omit) }}"
  when: influxdb_install_python_client
